### ISSUE TITLE
Effects don't stop when removed

### ISSUE THREAD

**Issue by JohnPaulHarold** [alemangui/pizzicato#1]
When removing an effect from a sound, I'd have expected the effect to stop, but instead the effect carries on modifying the source. You can see that the EffectsNode has been removed, it's not that removeEffect is doing nothing, just that it's not cancelling the effect that's been added.

I'd offer up sample code, but following the first example in the Effects section highlights the issue.

Is the above expected behaviour?

**Comment by alemangui** [comment]
It's indeed an error. The effect should stop modifying the source. Nice catch!

**Comment by JohnPaulHarold** [comment]
OK, glad it's been captured then. I was wondering if I was overlooking something and should have been setting the wetMix down to zero before removing the effect.

**Comment by alemangui** [comment]
Should be fixed now. Thanks for the heads up :)

**Comment by JohnPaulHarold** [comment]
The current fix kills the sound also, I'm not sure if that's intended or not. After I've removed an effect and hear nothing, I can `pause()` the `Sound` object created and then play it again, and it resumes on from it's last known position.

**Comment by alemangui** [comment]
You're right. This commit should take care of this.

d516f6ce71f33d4c3ba5467447548aa3714b8e30

**Comment by JohnPaulHarold** [comment]
Yeah, this is still with issues. I'm using stems, and so my `Sound` buffers are 4+ minutes long. Well, they're longer than simple soundfx samples at any rate. Adding effects seems fine, removing seems OK some of the time, but it will often lose sync and never recover that or worst case just stop making any sound from which it will also not recover.

**Comment by alemangui** [comment]
Interesting, could you maybe send me a URL or jsfiddle, jsbin or something similar?

**Comment by JohnPaulHarold** [comment]
I'll try and make a simple demo to highlight this. Later this week probably.

**Comment by JohnPaulHarold** [comment]
small example. http://webui.lt/pz_fx_test/examples/effects_on_off.html

In this test, you can fairly easily get the streams out of sync, but I couldn't replicate the sound completely dying and never returning. Where I was seeing that, I also had an analyser node wired in on each `Sound`. I could update the test later so each loop has a simple VU meter and see if that's an issue also. 


I can also upload the test to the repo, that way it can be tested locally.

**Comment by alemangui** [comment]
Indeed. This is a separate bug which is also evidenced in other areas of the library. Thanks for the catch. I have filed #9 to tackle it.

**Comment by shinedark** [comment]
hey im still having trouble removing  effects they stay loaded to the audio file. i got the latest version still doesn't work. here is a link to the code https://github.com/shinedark/samplerdj

**Comment by alemangui** [comment]
Hey @shinedark,

Took a look at your repo, looks pretty cool :)

I think the issue in your case might be the usage of jQuery's ```.keydown``` method, which is fired multiple times when the key is down, not just once. I believe this is what happens:

1. the user holds down one of the effect keys (let's say ```x``` for the delay),
2. jQuery's ```.keydown``` fires multiple times (let's say 10 times for this example), each time adding an effect via the code:
```javascript
sampler._aud.addEffect(dubDelay);
````
3. the pizzicato Sound now has the same effect instance added 10 times. This can be checked by using an undocumented property ```effects```. In your case, ```sampler._aud.effects```
4. now you release the ```x``` key. jQuery's ```.keyup``` is only fired *once*, as opposed to ```.keydown```. 
5. Pizzicato's ```removeEffect``` is only called once, and 9 other instances of the effect are still in the sound.

A workaround for your project is to make sure that you only add the effect once. 

A future discussion topic might be:

- Should Pizzicato allow adding multiple times the same effect? I tend to think so, it would make little sense to duplicate effects just to use them more than once.
- Should Pizzicato remove *all* instances of a particular effect when it's added more than once? Perhaps... currently it only removes the first it finds.

I hope this makes sense.

**Comment by shinedark** [comment]
thank you that fixed my problem
