### ISSUE TITLE
initializeWithBuffer

### ISSUE THREAD

**Issue by JohnPaulHarold** [alemangui/pizzicato#11]
for a project, I found myself needing a way to load in a set of sounds, but then to duplicate those sounds. It's for a simple loops based sequencer of sorts. What I ended up doing was loading in the sound files once, and then duplicating them as needed by copying the buffers from `getRawSourceNode()`, bypassing the need to create a whole new `Sound` object again. This might have been particular to my use case, and perhaps there's another way, but I added in `initializeWithBuffer` function, and then the option to create a `Sound` where the `source:` is `'buffer'`

If you feel like examining this some more, I can push my quick branch and then review it.

**Comment by alemangui** [comment]
Sorry for the delay, hectic week!

Your use case sounds interesting indeed. If I understood correctly the idea is to have several Sound objects stemming from the same audio file without the need for re-downloading the file right?

What if we could have a more generic initialization from another Pz.Sound object? Something like:

```javascript
snare = new Pz.Sound('./audio/snare.m4a');
snareCopy = new Pz.Sound({ 
    source: 'sound', 
    options: { sound: snare } 
});
```

or a way of creating copies of sounds by a copy function

```javascript
snare = new Pz.Sound('./audio/snare.m4a');
snareCopy = snare.copy(); 
```

Would this work for the case you described?

**Comment by JohnPaulHarold** [comment]
Likewise, apologies for my lateness of reply. Yes, that's pretty much it and you've understood what I meant despite me wording it poorly :-) I'll have a look and see if I can implement both of those, but I'm not sure when that will happen.

**Comment by alemangui** [comment]
I've added a ```clone``` method in Pizzicato.Sound objects. It can be found con commit https://github.com/alemangui/pizzicato/commit/a0d516cce7f65b07b48f7606c7fbb693026624be

Feel free to take it for a spin before I push a new version. Any remarks are welcome in this thread.

**Comment by JohnPaulHarold** [comment]
My apologies for only just replying, I've been a bit ill this weekend. I'll try and give this a spin later this week. Nice work.

**Comment by JohnPaulHarold** [comment]
@alemangui this clone method does pretty much what I hacked together and is cleaner to boot. Many thanks. My use case was I didn't want to be reloading files I'd loaded and stored previously, and this does that. Many thanks for this change.

**Comment by alemangui** [comment]
Cool, happy it worked :) And thanks for the new PRs, I will take a look at them soon.

Cheers!
