### ISSUE TITLE
Reroute Sound destinations

### ISSUE THREAD

**Issue by JohnPaulHarold** [alemangui/pizzicato#16]
I have a need to create `Sound` objects, but send them to a `splitter`, and then connect the `splitter` to the `context.destination`, but I'm not seeing how this can be done currently. 

My use case is that I'd like to split the signal of many/some/one `Sound` object(s), add an `analyser` to each channel of the `splitter`, and then connect the `splitter` to destination. I don't have a need for analysers per `Sound` object. Is this possible in the current Pizzicato?

**Comment by alemangui** [comment]
Have you tried using the ```masterVolume``` node?

This is an undocumented node at the end of the audio graph representing a Pizzicato Sound object. 

Image you have a Pz.Sound object with effects called ```sound``` and a splitter node called ```splitter```, you could maybe connect the output of the sounds to the splitter doing something like:

```javascript
sound.masterVolume.connect(splitter);
```

Then you can connect the different channels of the splitter to analysers.

Your case is interesting. I should think of a way of extending Sound objects in a more natural way and document it. In the meantime try the stuff above and let me know if it helped.

**Comment by JohnPaulHarold** [comment]
That works, thank you.

On your wider point, I was wondering if a Sound object would benefit for a property on the passed options object which defines an override output node. So, by default it routes to context.destination, or the node (splitter, something else), you've defined in the options. This is back of a napkin stuff, and I've done nil tinkering to see if this is workable, but it was rattling around while I hit this issue the other day. It might be too specific a fix for this particular use case.

I'll close this for now, as it resolves my immediate issue. A separate ticket can be raised for extending the Sound object. Else, I can reopen this.

**Comment by alemangui** [comment]
That's an interesting approach.

I currently have a pretty weak way of connecting an analyserNode (via the ```getAnalyser``` function). Needless to say, it's not useful when you need to fine-tune the audio graph.

I agree in that a constructor option to specify an array of nodes to connect to  (with a default of ```[Pz.context.destination]```) would be considerably more useful.

I will re-open this to keep it in mind.

**Comment by JohnPaulHarold** [comment]
this topic was rattling around with me again recently. I was wondering if the concept of grouping `Sound` objects was useful. A use case would be several drum kit samples, and you want to apply an effect to the grouping, or control gain/mute all sounds in the grouping.

**Comment by alemangui** [comment]
I am currently working on a commit - hopefully over soon - to allow connections between Pizzicato objects and web audio nodes, I think it's quite essential for a web audio library. This would allow to create groups of sounds using splitter and merger nodes - albeit in a rather creative way. I have created PR #23 to track this.

As a separate topic, the idea of grouping sounds had also crossed my mind. I can definitely see the use cases. I will try to envision an API and also create a separate PR for it.

**Comment by JohnPaulHarold** [comment]
just been reading https://github.com/alemangui/pizzicato/issues/23, very cool
