### ISSUE TITLE
Volume and other data for output graphs?

### ISSUE THREAD

**Issue by sksar** [alemangui/pizzicato#17]
How do i get a volume and other such information out of individual sound sources? Please list all of the available data..

**Comment by JohnPaulHarold** [comment]
```
var sound = new Pizzicato.Sound('path/to/your/sound.wav', function () {
  console.log('loaded sound and the volume is ', sound.volume);
});
```

the above should give you the current volume of the created `Sound` object. What other info do you need access to?

**Comment by sksar** [comment]
What are the list of info available? I want all to know all that is available..

**Comment by alemangui** [comment]
There are indeed a few undocumented parameters for the Sound object:

- ```volume```, as @JohnPaulHarold pointed out, will give you the volume at which the sound is playing
- ```attack``` will give you the attack time (also called fade-in)
- ```sustain```will give you the sustain time (also called fade-out). This one is useful to avoid clicks.
- ```loop``` will tell you if the sound is meant to keep going in loops (only applicable for sounds from files)
- ```frequency``` will tell you the frequency of the sound (only applicable for sounds from wave/oscillators)
- ```playing``` will tell you if the sound is ongoing (not stopped nor paused)
- ```effects``` will give you an array of the effects currently applied to that sound. You shouldn't modify this directly though, you should use the ```addEffect``` and ```removeEffect``` methods.

There are also some properties for the effects. All of these should be added to the readme documentation. I'll get to that in the next few days.

Cheers,

**Comment by JohnPaulHarold** [comment]
@alemangui do you think it's worth adding a JSDoc process to the gulp file and slowly adding appropriate comments to the codebase?

**Comment by alemangui** [comment]
@JohnPaulHarold I have mixed feelings about comments in the codebase. I will try to take a decision before a 1.0 version though :)

On one hand, there's obvious advantages to using comment-doc generation (à la Docco, JSDoc, etc). On the other, I doubt it's useful to expose the comments of all parts of the code - i.e., there are some functions and properties that probably should remain being "internal". So whereas the comments will undoubtedly be helpful to someone trying to _understand_ the code, they might make too much noise to someone simply trying to use it.

There's also the possibility of simply commenting it and not generate a documentation page out of the comments...

I'll keep gnawing on this for the next few days

**Comment by alemangui** [comment]
I'd rather keep this open until they are in the readme file
