### ISSUE TITLE
Node/Angular Support

### ISSUE THREAD

**Issue by rhsu0268** [alemangui/pizzicato#19]
How do I import this great module via a node/angular setup?

**Comment by JohnPaulHarold** [comment]
@rhsu0268 glad you raised this, I was about to ask about AMD/Module support as well +1

**Comment by alemangui** [comment]
Yep, this is definitely needed. I'll take a look.

**Comment by alemangui** [comment]
Commit dcbde030baa4770b7fb355204ed3166920bf61a0 adds support for both AMD and CommonJS modules. Please take it for a spin and let me know if it has any issues on your side.

**Comment by alemangui** [comment]
Support for AMD and CommonJS should be up and running since version 0.3.1. I will close this issue, but feel free to reopen it if you have issues. Cheers.
