### ISSUE TITLE
Reverb / Convolver effects

### ISSUE THREAD

**Issue by JohnPaulHarold** [alemangui/pizzicato#2]
Do you have any plans to add convolver effects to Pizzicato? Reverb and the like.

I ask, partly to find out if you're working on it already. I've also spent the evening hacking it in myself,
https://github.com/JohnPaulHarold/pizzicato/tree/effect_reverb

**Comment by alemangui** [comment]
Hey man, yep! reverb would be an awesome addition to the library. Even though I'm not currently working on it, it's definitely high on my list of wanted features.

The issue I have with reverb is related to the sound sample that the convolver node uses to shape the convolution. This means we either:

1. Make an ajax request to load a sample file to use for the convolver node.

The problem with this is that the asynchronous nature of the ajax request will mean that the effect can't be used imediatly after being created, making this kind of code impossible:
```javascript
var reverb = new Pz.Effects.Reverb(...);
sound.add(reverb);
```
Some callbacks could be used, but it would still feel strange to have the reverb behave differently than all the other ones.

2. Make a programmatic reverb effect without an external sample file.

This would be nice but I'm not sure how to approach it. There are a few projects and examples out there which programmatically create the reverb effect by creating buffers and populating them according to the specified decay. Doing so would enable us to have something like:
```javascript
var reverb = new Pz.Effects.Reverb({ decay: x, .... });
sound.add(reverb);
```

Maybe a combination of both could work, in which the user can decide whether to programmatically specify some parameters or to provide a sample file for the convolver to munch on.

**Comment by JohnPaulHarold** [comment]
> The issue I have with reverb is related to the sound sample that the convolver node uses to shape the convolution.

Yes, so far I've only approached option 1.
    var reverb = new Pz.Effects.Reverb({impulse: './path/to/your/impulse.wav'}, function () {});
    sound.add(reverb);

**Comment by alemangui** [comment]
> I think initially it was weird to me, compared to the other effects, but I saw it in much the same way as loading a Sound file vs generating one.

Yep, that's true...

The library at https://github.com/adelespinasse/reverbGen looks pretty good. I found this one as well that could give us a hint: https://github.com/web-audio-components/simple-reverb

**Comment by JohnPaulHarold** [comment]
Yes, I found that simple-reverb project later on, and it looks like p5.js uses that for their simple [reverb](https://github.com/processing/p5.js-sound/blob/master/src/reverb.js#L157-L180) also. 

I haven't made a PR yet, but can do if it will help to start discussing how this should look, API wise, code wise etc. My initial thoughts were that the params would be slots added to the options object, and then in the `Effect` determine if the Reverb is using a file or not and decide to ignore certain option slots.

**Comment by alemangui** [comment]
What about having them as separate effects... _i.e.,_ a ```Convolution``` and a ```Reverb``` one.

The ```Pz.Effects.Convolution``` would require the impulse file and thus would be asynchronous. An API could look like:

```javascript
var convolution = new Pz.Effects.Convolution({
  impulse: './sample.wav',
  mix: 0.5,
  callback: function() {...}
});
```

Whereas the ```Pz.Effects.Reverb``` would be an algorithmic non-async reverb:

```javascript
var reverb = new Pz.Effects.Reverb({
  decay: 2,
  mix: 0.5,
  ...
  ...
});
```

This way we avoid the potential confusion of using conflicting/separate options in a reverb constructor.

**Comment by JohnPaulHarold** [comment]
OK, I'm down with that. I'll rename what I have and see about making a PR. You think you'd prefer the `callback` to be a slot on the `options` object? Currently it's another param on the constructor. It's only like that because I followed the `Sound` constructor approach, but going with it as an option would perhaps make it more consistent with the other effects.

**Comment by alemangui** [comment]
You're right. The callback should be outside the ```options``` object, like in the Sound constructor :)

**Comment by JohnPaulHarold** [comment]
hmm, this generated reverb is failing tests, and I don't quite understand why at the moment.

**Comment by alemangui** [comment]
Regarding the first pull request (the merged one) I might dive into making a few changes - the main one being making the impulse file readonly and settable only in the constructor. 

The reason being that - after initialization - using a simple setter gives the user no way to know when the file has been loaded (async with a lack of callback). I don't think the use-case of dynamically changing the impulse file of a convolver effect is common enough to warrant this feature, do you agree? 

If the use-case proves to be worth it, a separate method receiving a path and a callback could be implemented. (something like ```updateImpulse(path, callback)```)

I will take care of this, most likely in a different issue.

**Comment by JohnPaulHarold** [comment]
Writing the impulse loader approach, and also porting over the generated reverb have been interesting. I'm a bit stumped as to why the tests are failing for the `Effects.Convolver()`, if you have the time to look at the PR and perhaps offer some help as to why that would be appreciated.

Considering what you said about the Ping Pong Delay, I was wondering if it would be worthwhile to find some good, quality, free to use impulse wavs, and make reverb `Effect` variants. Something like, `Pz.Effects.RoomReverb(options)` or `Pz.Effects.SpringReverb(options).` Kind of like built in, sane defaults. Along with an option to load you own impulse, via `Pz.Effects.Reverb` How would you feel about that? 

As for dynamically changing the impulse, I'm think I'm in agreement with you. I wired that in as it felt like the code was moving towards that, but on reflection, I think you could just argue that the user should remove the current `Effect.Reverb` and create a new one, it's essentially what's happening anyway.

**Comment by alemangui** [comment]
Thanks, I will take a look at the other PR for the reverb. 

While I like the idea of impulse wavs, I would prefer not to include them in the core library for weight reasons. We can either have them in the demo site or create a different repo to somehow extend the reverb. We can of course re-consider this if at some point we feel it could be useful.

**Comment by alemangui** [comment]
Regarding the convolver effect:
I have removed the possibility of getting or setting an impulse file in the convolver effect. I don't see a reason to access this property after initialization. Also, the console will log an error if we try to create a convolver effect without an impulse file (although no exception will be raised).

Regarding the reverb effect:
I have renamed the parameter ```seconds``` into ```time``` for consistency with the Delay, Ping-Pong and Flanger effects. I have also set 'min' (0) and 'max' (10) values for decay and time. If these seem insufficient, feel free to open a separate issue.

The commit that addresses these issue is [here](https://github.com/alemangui/pizzicato/commit/d524d8f9f620e807d0496fa0b567fd2acff054bd)

Examples are also now in the website version:
Reverb: https://alemangui.github.io/pizzicato/#reverb
Convolver: https://alemangui.github.io/pizzicato/#convolver

I will close this issue, but feel free to open new ones if remarks or suggestions arise while using these new effects.

**Comment by JohnPaulHarold** [comment]
>   I have also set 'min' (0) and 'max' (10) values for decay and time. If these seem insufficient, feel free to open a separate issue.

for the max, 10 seconds is probably enough, however, I ran into issues creating a buffer when the min was set at zero, which is why I set it to just above. Did you not see these issues yourself?

**Comment by alemangui** [comment]
Yep I had them as well. ```time``` can't be zero, so I have a min of 0.0001 for that parameter
