### ISSUE TITLE
Wording for "Attack/Sustain" is incorrect

### ISSUE THREAD

**Issue by EdenSG** [alemangui/pizzicato#20]
The correct terms are *attack* and *release*, not *sustain*. Check [wikipedia](https://en.wikipedia.org/wiki/Synthesizer#Attack_Decay_Sustain_Release_.28ADSR.29_envelope) for a more complete explanation.

**Comment by alemangui** [comment]
You are indeed correct. The naming was inspired by the piano _sustain_ pedal, but I agree in that the correct audio term is _release_ and sustain may cause more confusion than good. 

I need to think about when to roll this change given that the rename would be breaking. Perhaps deprecating _sustain_ first for a few versions would be acceptable. I'll keep this open in the meantime.

**Comment by JohnPaulHarold** [comment]
You could change `sustain` to an alias of `release` and act as usual but with an added  deprecation `warn()` as you suggest, and of course add the correct `release` option and change the docs to reflect the newer wording, perhaps with an additional note about the change. As it's a breaking change, I guess a bump from v0.3.x to v0.4.x would be required.

@alemangui do you have any idea how many projects in the wild are using your lib? That's probably a good indicator as to how disruptive this change will be at this point in the library's lifecycle.

**Comment by alemangui** [comment]
Sustain is now deprecated - but still usable to avoid breaking changes. Retain is now the officially documented way to do things. 

This fix will be included in next release. Thanks guys.
