### ISSUE TITLE
Change path source file

### ISSUE THREAD

**Issue by edgehero** [alemangui/pizzicato#24]
how do i change the source path ( from external file )?

```
source = new Pizzicato.Sound();
source.path = "/link/to/steam.mp3";
```

Sadly this does not work.

**Comment by alemangui** [comment]
Hey, 

Once the Pz.Sound object is initialized you can't change its source. If you want to have a Sound from an external file you have two options:

The shortcut:
```javascript
source = new Pizzicato.Sound('link/to/stream.mp3');
```

The long version:
```javascript
source = new Pizzicato.Sound({
    source: 'file',
    options: { path: 'link/to/stream.mp3' }
});
```

You can also add a callback to know when the file has been loaded and decoded:
```javascript
source = new Pizzicato.Sound({
    source: 'file',
    options: { path: 'link/to/stream.mp3' }
}, function() {
    console.log('sound file loaded!');
});
```
