### ISSUE TITLE
Any way of setting play Rate?

### ISSUE THREAD

**Issue by edgehero** [alemangui/pizzicato#25]
First i got to say that pizzicato is awesome till now, awesome work on it :) 

But is there also a way to set the play rate? (play speed)
Something like this example:
http://webaudiodemos.appspot.com/wubwubwub/index.html

you can set rate 1 for normale speed, 0 for pause  and -1 for going backwards.
Is that something that can also be accomplished with pizzicato?

**Comment by alemangui** [comment]
Hey, thanks a lot :) It's unfortunately not possible now, but this is something I'm very interested in. Pitch and speed manipulation is in the list of features to come. Thanks for sharing the link.

**Comment by edgehero** [comment]
ok currectly not a work around for that either? :-/

**Comment by alemangui** [comment]
Unfortunately not. The only easy thing to do so far is change the playbackRate manually. This will also change the pitch though, which is unwanted :(

**Comment by edgehero** [comment]
Yea, i found this way. but it will give that pitch chipmunchs effect ;).
source.sourceNode.playbackRate.value = 2;

**Comment by alemangui** [comment]
I'll close this one in favor of #15 (pitch effect feature)
