### ISSUE TITLE
Is it possible to change an effect without removing it?

### ISSUE THREAD

**Issue by edgehero** [alemangui/pizzicato#28]
Im currently using effects something like this:
```
.removeEffect(effect); // remove old effect
effect = Create new effect // create new effect
.addEffect(effect); // add new effect
```

But is it also possible to change an effect? like effect(value: 1); 
because removing and adding it again, creates alot of laggs and delays

**Comment by edgehero** [comment]
foudn the solution source.effect[0].value =

**Comment by alemangui** [comment]
I'm a bit late, but yes, you can find all added effects under the ```effects``` array.

Alternatively, you can store the effects in a variable to access them later. For example:

```javascript
var delay = new Pz.Effects.Delay();
var sound = new Pz.Sound();

sound.addEffect(delay);

// modify the delay's time - no need to remove it from the sound
delay.time = 0.09;
```
