### ISSUE TITLE
SFZ wave files in Pizzicato

### ISSUE THREAD

**Issue by wildfiremedia** [alemangui/pizzicato#30]
What is the recommendation to load 88 wave files that use with SFZ format, contains wave files of 1MB+ each and good enough to run on Pizzicato?

What is the maximum channels we can play from wave file?

**Comment by alemangui** [comment]
I'm not aware of a full fledged tool/library to use sfz format with web audio, nonetheless, if you just want to load the wave files and play them, you can try creating individual ```Pz.Sound``` objects.

```javascript
var c5 = new Pz.Sound('./audio/c5.wav');
```

It wouldn't surprise me to see some performance issues with 88 objects that have a 1MB+ size each, but given that this is uncharted territories, I am pretty interested in the outcome - after which we can think how we can optimize.
