### ISSUE TITLE
Setting an effect's object parameters after it is created

### ISSUE THREAD

**Issue by midipixel** [alemangui/pizzicato#35]
Hi @alemangui . Thanks for creating Pizzicato. It is a nice and friendly API that makes working with web audio painless! :)

I'm using it to make a sampler where I want the users to be able to change the effects parameters to craft their sound. So far, I've been able to do this with the sound object's "options" (for example, setting a new attack value works), but not by assigning new values to an effect's "options" object. I assume that these parameters are assigned to the nodes of the effect chain upon creation, and then they won't set their corresponding values again.

So, is there a way to set an effect parameters after they're created other than messing directly with the effect's audio nodes?

Here's a small sample of what I'm trying to do:

```
var tremolo = new Pizzicato.Effects.Tremolo({
    speed: 5,
    depth: 1,
    mix: 1
});
sound.addEffect(tremolo );
tremolo.speed = 15;

sound.play(); 
//Speed is still 5. Can I set it to 15 without directly manipulating the nodes?
```

Thanks in advance!

**Comment by JohnPaulHarold** [comment]
hi @midipixel, I've just tried doing the same as you, same effect, and loading a sound file, and stuff works; I heard a really fast tremolo speed. This doesn't discount that you have an issue, but can you also let us know what OS, browser you are on? Or indeed, anything else that might be of interest. I tested your exact steps on Windows10, Chrome latest. FYI, I loaded a sound file:

**Comment by JohnPaulHarold** [comment]
Glad that's resolved. You OK to close the issue also? Interesting you mention a sampler, one of my WebAudio todos has been to make a simple wave editor; trimming, cropping essentially, with an equally simple GUI on top.

**Comment by midipixel** [comment]
Of course, I'll close it now!

Yes, having trimming and cropping would be really useful. In my case, the app would be really well served with a simple audio editor with UI/features somewhat similar to [this one](http://www.chocopoolp.com/bhajis/imgs/fx_menu.gif)

If I manage to implement it, I'll get in touch. ;)
