### ISSUE TITLE
Retrieve sound data for upload

### ISSUE THREAD

**Issue by SirCameron** [alemangui/pizzicato#36]
Once a sound is recorded, and maybe some effects have been added, Is it possible to retrieve the sound data to be uploaded to server?

**Comment by proyb6** [comment]
You can add sound effects to the stop button and upload file is using XHR method of any audio file saved on your temporary to the server's storage.

**Comment by SirCameron** [comment]
Thanks, my question is, though: what function can I use to get the sound data as a string or buffer to be uploaded using XHR? I don't want to save the file locally first.

**Comment by proyb6** [comment]
This is harder to implement either upload by binary or base64, will be best answer by others.

**Comment by SirCameron** [comment]
Uploading is not the problem.

How can I save a sound file using Pizzicato? There isn't anything in the documentation.

**Comment by alemangui** [comment]
Hey,

There is no built-in functionality in Pizzicato to save a blob of audio that can be later sent to the server or written in a file.

Nonetheless, you can take a look at MDN's documentation for the [MediaStreamAudioDestinationNode](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioDestinationNode). The article includes a way of recording a blob representing the audio data.

Pizzicato can coexist with other AudioNodes, including the MediaStreamAudioDestinationNode (more info [here](https://github.com/alemangui/pizzicato#sounds-connect) and [here](https://github.com/alemangui/pizzicato#effects-connect)), so you can easily create a Pizzicato Sound object and connect it to a MediaStreamAudioDestinationNode and do your magic.

**Comment by SirCameron** [comment]
Awesome @alemangui ! thanks!
