### ISSUE TITLE
Preamp or loudness

### ISSUE THREAD

**Issue by proyb6** [alemangui/pizzicato#37]
Some audio source or wave may sound tinny, are there any way to increase loudness or preamp that found in music players? Would be great for improve music quality

**Comment by alemangui** [comment]
Pizzicato is limited in the volume output of the Sound objects, but there is a workaround:

1. Create a detached Sound object ([details here](https://github.com/alemangui/pizzicato#creating-a-detached-pizzicatosound-object))

This sound object will not be automatically connected to the destination, which means you can connect it manually.

2. Connect the sound to a gainNode, and then the gain node to the destination:

```javascript
gain = Pz.context.createGain();
sound.connect(gain);
gain.connect(Pz.context.destination);
```

You will then be able to raise the gain as much as you want. The gain node is basically a multiplier, so you can try any values to see which one fits, like:

```javascript
gain.gain.value = 1.5
```

**Comment by proyb6** [comment]
Do you mean createAnalyser instead of createAnaliser?

Not sure if the code is correct, I still hear the volume at the same level as 100% normal volume.
```
var analyser = Pizzicato.context.createAnalyser();
var a = new Pizzicato.Sound('./1.flac', function() {
    options: { 
        detached: true 
    }
});
a.attack = 0;
a.release = .8;
a.connect(analyser)

gain = Pz.context.createGain();
a.connect(gain);
gain.connect(Pz.context.destination);
gain.gain.value = 2

```

**Comment by alemangui** [comment]
No need for the analyser (but thanks for pointing out the typo :) )

```javascript
var a = new Pizzicato.Sound('./1.flac', function() {
    options: { detached: true }
});
a.attack = 0;
a.release = .8;

gain = Pz.context.createGain();
a.connect(gain);
gain.connect(Pz.context.destination);

gain.gain.value = 2
```

**Comment by proyb6** [comment]
There is one issue if adding convolver to ```var a```, will cause all gain to be increase to 2. Without convolver, I can hear the difference gain between each keys.

```
<script src="./Pizzicato.min.js"></script>
<p onmousedown="d()" onmouseup="u()">A key</p>
<p onmousedown="d2()" onmouseup="u2()">B key</p>
<p onmousedown="d3()" onmouseup="u3()">C key</p>

var a = new Pizzicato.Sound('./1.flac', function() {
    options: { detached: true }
});
a.attack = 0;
a.release = .8;

var a2 = new Pizzicato.Sound('./2.flac', function() {});
a2.attack = 0;
a2.release = .8;

var a3 = new Pizzicato.Sound('./3.flac', function() {});
a3.attack = 0;
a3.release = .8;

var convolver = new Pizzicato.Effects.Convolver({
    impulse: './c.wav',
    mix: 0.4
}, function() {
    console.log('Convolver ready to be used.');
});

a2.addEffect(convolver);
a3.addEffect(convolver);

gain = Pz.context.createGain();
a.connect(gain);
gain.connect(Pz.context.destination);

gain.gain.value = 2

//This code still overriding the gain, to appear the same volume as non-detached sound. I tried to 
//move the code before ```gain = Pz.context.createGain();```, is still being override.
a.addEffect(convolver);

function d() {
a.play();
}
function d2() {
a2.play();
}
function d3() {
a3.play();
}

function u() {a.stop();}
function u2() {a2.stop();}
function u3() {a3.stop();}
```

**Comment by proyb6** [comment]
Is this the expectation behaviour or a bug?

**Comment by alemangui** [comment]
It's not expected behavior, sounds like a bug. I will take a look.

**Comment by alemangui** [comment]
Definitely a bug. When adding a single effect to multiple sounds, the output of the effect remains connected only to the last sound added.

**Comment by alemangui** [comment]
I have created issue #40 for following this problem - given that this one talks mainly about preamp.

**Comment by alemangui** [comment]
@proyb6  There might be a workaround by creating your own audio graph.

To do so, instead of adding effects using ```addEffect``` you can try to:

1- Create only detached ```Pz.Sound``` objects (all of them).
2- Create the preamp gain and connect it to the desired sound as before. At this moment you should have something like:
```
[s1]-[gain(2)]
[s2]
[s3]
```
3- Create a gain to unite all sounds and connect it to your desired effect.
```
[s1]-[gain(2)]--|
[s2]-----------|--[gain]--[convolver]
[s3]-----------|
```
4- Connect the convolver to the destination
```
[s1]-[gain(2)]--|
[s2]-----------|--[gain]--[convolver]--[destination]
[s3]-----------|
```

An example of this is done here: https://jsfiddle.net/udzutzLj/2/
