### ISSUE TITLE
Render convolution effect on one master source?

### ISSUE THREAD

**Issue by proyb6** [alemangui/pizzicato#38]
If we have hundreds of audio files, attach convolution to each audio will consume huge memory usage. Not sure if there are ways to stream multiple sounds to master source and render realtime with convolution?

**Comment by alemangui** [comment]
I don't know if I'm understanding this correctly, but I think you mean you don't want to create n convolution effects for n Sound objects, am I right?

Anyway, If you start experiencing performance problems you might want to try connecting Pizzicato objects with AudioNodes manually - similar to the last comment I posted in issue #37. This will allow you to merge all your Pizzicato.Sound objects to a single node that can then be connected to whatever you need.

**Comment by proyb6** [comment]
To clarify, if I have hundreds of sound files, it will incur lot of memory

More memory:
Sound1 + add Convolution effect = 20MB
Sound2 + add Convolution effect = 20MB
Sound3 + add Convolution effect = 20MB
...
Sound100 + add Convolution effect = 20MB

Less memory:
Sound1 -|
Sound2 -|--- Feed into one channel and apply with convolution effect
Sound3 -|
...
Sound100

**Comment by alemangui** [comment]
To achieve that check my last comment in #37, you can create all Sounds as detached and then use `.connect()` to merge them to a gainNode. Then you can connect the gainNode to the convolver also using `.connect()`.
