### ISSUE TITLE
Can't use it with local file:// protocol

### ISSUE THREAD

**Issue by 123Jon4** [alemangui/pizzicato#45]
I would like to use Pizzicato with local files, like with Howler.

**Comment by 123Jon4** [comment]
I read some articles and it seems not to be possible because JavaScript cannot go outside the sandbox.

**Comment by alemangui** [comment]
Pizzicato uses AJAX requests to fetch the audio files. If you want to use local files you'll need to start a local server.

If you have Python installed, you can just open the Terminal, go to the folder where you have your html file and audio files, and type ```python -m SimpleHTTPServer```. You'll have a server up and running in no time.
