### ISSUE TITLE
Uncaught TypeError: this.getRawSourceNode is not a function

### ISSUE THREAD

**Issue by jerrojelly** [alemangui/pizzicato#46]
On Google Chrome console:
```
Uncaught TypeError: this.getRawSourceNode is not a function
    at Pizzicato.Sound.value [as getSourceNode] (Pizzicato.js:733)
    at Pizzicato.Sound.value [as play] (Pizzicato.js:428)
    at pz2.html:26
```

```
var k1 = new Pizzicato.Sound("assets/piano/"+piano[0]+".wav");
k1.play()
```

There is a wave file existed and loading file is fine except getRawSourceNode is?

**Comment by jerrojelly** [comment]
This is working fine, something was changed?
```var k1 = new Pizzicato.Sound("assets/piano/"+piano[0]+".wav", function() { k1.play() });```

**Comment by alemangui** [comment]
Loading a sound from an external file is an asynchronous process. In other words, when you get to ```k1.play()``` the network request needed to fetch the file hasn't completed yet.

This is why you can pass a callback function as argument. This function will be called when the file loads. For example:

```javascript 
var k1 = new Pizzicato.Sound({ 
    source: 'file',
    options: { path: "assets/piano/"+piano[0]+".wav" }
}, function() {
    k1.play;
});
```

**Comment by Jacob8765** [comment]
I also have this problem. I tried the solution @alemangui posted and the page loads, but no sound plays. I am using the npm version on React.

**Comment by alemangui** [comment]
Hey can you post the code you are using to take a look?
