### ISSUE TITLE
playing sound at a precise timeline value 

### ISSUE THREAD

**Issue by gimyboya** [alemangui/pizzicato#49]
I have the following scenario:
1- Open an audio file with `pizzicato`
2- Get the desired starting point time on the timeline from a user triggered event 
3- Pass the time to `pizzicato` to start playing the audio at the exact time specified

Now the question is how can i do that i didn't see an example showing that and is it even possible to do it with `pizzicato`?

**Comment by alemangui** [comment]
You can pass two parameters into the ```play``` function: ```when``` and ```offset``` ([docs](https://github.com/alemangui/pizzicato#play-example)).

Maybe the offset is what you are looking for. For example, if you wanted to start a sound at second 3, you could do:

```javascript
sound.play(0, 3)
```

**Comment by gimyboya** [comment]
Thanks for your reply i think it's what i need
