### ISSUE TITLE
Bug in removeEffect 

### ISSUE THREAD

**Issue by hcollin** [alemangui/pizzicato#51]
Hi,

While playing around with Pizzicato for my Web Audio Speech I ran into a problem. I created a simple page that uses microphone as an input and by pressing a button you can add effects to it. All fine and well and works great until you try to remove an effect. If the effect that is being removed is not the first effect the pizzicato produces an error:

Uncaught TypeError: this.effectConnectors is not a function

I traced the problem to this line 382 in file Sound.js:
`
var previousNode = (index === 0) ? this.fadeNode : this.effectConnectors(index - 1);
`

When index is not 0, this line fails as the this.effectConnectors is an array, not a function. So by changing the line to:

`
var previousNode = (index === 0) ? this.fadeNode : this.effectConnectors[index - 1];
`

fixed the problem. I have done this same mistake so many times... 

Best Regards,

Henrik Collin

edit: fixed a typo

**Comment by alemangui** [comment]
Good catch. This is a regression of the latest version. Your fix is indeed correct, I will incorporate your PR #52 and release a new minor version.

**Comment by hcollin** [comment]
Great! You can find the demos from my repo if you are interested.

Cheers!

**Comment by alemangui** [comment]
Issue should be solved in 0.6.1.

**Comment by bogolubow** [comment]
Hi! I have version 0.6.1 instaled from npm but in dist folder i have still `this.effectConnectors(index - 1)` -> 1011 line ;
