### ISSUE TITLE
Changing sound's filepath

### ISSUE THREAD

**Issue by epiqueras** [alemangui/pizzicato#54]
Is it possible to change a sound's file path and have it load the new sound?

**Comment by JohnPaulHarold** [comment]
@epiqueras what's he use case stopping you from just creating a new `Pz.Sound()`?

**Comment by epiqueras** [comment]
@JohnPaulHarold #53 , stops me from creating more sounds each time the file path changes, because eventually all sounds will stop.

**Comment by JohnPaulHarold** [comment]
@epiqueras https://github.com/alemangui/pizzicato/issues/53 alludes to a use case whereby you need a massive amount of concurrent sounds, each with presumably something different a-happening. This issue reads like a potentially different use case. Can you detail what you are trying to achieve.

**Comment by epiqueras** [comment]
I worked around #53 by modifying the existing sounds instead of creating new ones every time a user changes the configuration. The only property I can't seem to change is the file path. I was wondering if there was a way to change it to avoid creating a new sound and possibly running into #53 after users change a sound's file path multiple times.

**Comment by alemangui** [comment]
This is not possible at the moment. If the workaround proposed in #53 does not fit your use case we can further discuss of the best way to have this feature in.
