### ISSUE TITLE
Group don't work

### ISSUE THREAD

**Issue by alammm** [alemangui/pizzicato#60]
Hi team, first: thanks for this library it's rock!
Second: I have a issue with group.play()

I test this code: 

var drums = new Pizzicato.Sound('./audio/drums.mp3');
var guitar = new Pizzicato.Sound('./audio/guitar.mp3');
var bass = new Pizzicato.Sound('./audio/bass.mp3');

var group = new Pizzicato.Group([drums, guitar]);

group.addSound(bass);
group.play();

And I have a error... I test others method ('wave') and individual sound and work! But group  cause an error for me...

Please I need your help.
Thanks!

**Comment by proyb6** [comment]
What is the error message?

**Comment by alammm** [comment]
Hi @proyb6 thanks for your reaction.

this is the error "this.getRawSourceNode is not a function".

now i find a solution... 

var kick = new pizzicato.Sound('./assets/sounds/kick.wav', function() {
      var hihat = new pizzicato.Sound('./assets/sounds/hh.wav', function() {
        var snare = new pizzicato.Sound('./assets/sounds/snare.wav', function() {
          // Sound loaded!
          var group = new pizzicato.Group();
          group.addSound(kick);
          group.addSound(hihat);
          group.addSound(snare);
          group.play();
        });
      });
    });

i think, the problem is the time on load each sound... i think in my errorCode the function play is execute before load all sounds... now i charge one by one and then execute play().

Thanks for your time, and thanks for this library!!

**Comment by alp2201** [comment]
I'm having the same problem! When I tried the above solution, it blocked a cross origin request, and when I fetch the files sequentially I get the "this.getRawAudioSource is not a function" error.

**Comment by alp2201** [comment]
Actually, I got this to play the 2 tracks simultaneously with no errors! Thanks for your comment alammm!

var group = new Pizzicato.Group();
var track1 = new Pizzicato.Sound('./GB1.mp3', function() {
group = new Pizzicato.Group();
group.addSound(track1);
});
var track2 = new Pizzicato.Sound('./Crunk_House_1.mp3', function() {
group = new Pizzicato.Group();
group.addSound(track2);
group.play();
});
