### ISSUE TITLE
Can not do a function waveform of mic or audio

### ISSUE THREAD

**Issue by aahedi** [alemangui/pizzicato#64]
Is it can do a function like this:

if waveform is low then hide image, else show image.

repeating function on when playing audio

Example:
![audio-waveform](https://user-images.githubusercontent.com/8935884/27990831-7dd6aef4-648d-11e7-8aca-7bee5cf6c161.png)

**Comment by alemangui** [comment]
Hey, this is not a main use case of Pizzicato. However, you can likely achieve it by attaching an `analyserNode` to the `Pz.Sound` object and checking the values returned by the `analyserNode` to trigger the show/hide of the image.

You have an example of attaching an analyser node to a `Sound` object here: https://github.com/alemangui/pizzicato#connecting-nodes-to-a-pizzicatosound-object
