### ISSUE TITLE
use in angular/typescript

### ISSUE THREAD

**Issue by malorus** [alemangui/pizzicato#65]
Hi there, I accidently discovered this lib and it really looks great, congratulations guys. But how to incorporate this lib into typescript? I'm developing with angular, so usually I import the classes I need. I have already tried 
`import {Pizzicato} from 'pizzicato'` 
but it didn't work. I get an error:
`ERROR ReferenceError: Pizzicato is not defined` 
It only works when using the cdn-style. But I'd like to import pizzicato in a  typescript-file. Any suggestions?

**Comment by malorus** [comment]
I solved it on my own. In Pizzicato.js I added:

`	if (commonJS)
		module.exports.Pizzicato = Pizzicato;`

And inside my typescript-file I import it this way:

`import { Pizzicato } from "pizzicato/distr/Pizzicato";`

Now it works perfectly.

**Comment by alemangui** [comment]
Hey, good to know you found a solution :)

**Comment by koraysels** [comment]
here is a solution without having to patch the node_modules folder 

`import * as Pizzicato from 'pizzicato/distr/Pizzicato.js';`
