### ISSUE TITLE
callback after end of sound

### ISSUE THREAD

**Issue by malorus** [alemangui/pizzicato#66]
Hi, me again :)
I just thought it would be a good idea if there would be a listener for the end of a soundfile. I searched in the docu for such a callback but couldn't see anything. There are use-cases, where you want to take some actions after the end of the file has been reached. It would be great to have something like:

```javascript
let sound = new Pizzicato.Sound('audio.mp3', function () {            
    sound.play();	
    sound.on('end', function() {
        // do some stuff after reaching the end of the file
    });		
});
```

by the way, I've just found an issue [right here about trigger-events at the end of a file](https://github.com/alemangui/pizzicato/issues/10). So is a trigger already implemented? I ask as I can't see anything in the official doc.

**Comment by alemangui** [comment]
Hey, actually there is currently an event launched when a sound is over, and it works exactly as you suggested it:

```javascript
sound.on('end', function() {
});	
```

There are four events you can listen to: ```play```, ```pause```, ```stop``` and ```end```

You can see an example in the Sound test file at ```tests/Sound.test.js```.

I will maintain this issue open until these are documented in the ```Readme.md``` file.

**Comment by malorus** [comment]
As I have just discovered, such a callback is already implemented. But as it is not mentioned in the documentation, I thought it is not present. So, for all those ones searching in the future for a callback after the file has finished playing, the above mentioned listener will work:

```javascript    
sound.on('end', function() {
    // do some stuff after reaching the end of the file
});	
```

**Comment by alemangui** [comment]
I will keep this open until documentation for all events is added.

**Comment by alemangui** [comment]
Documentation on events added.
