### ISSUE TITLE
sound.release has no effect

### ISSUE THREAD

**Issue by malorus** [alemangui/pizzicato#67]
Can anyone confirm that the release has no effect?

```javascript
var sound = new Pizzicato.Sound();
sound.release = 0.9;
```

Attack works fine, but release does not. Even with a value of 10 the sound stops abruptly. There is no fade-out effect.

**Comment by alemangui** [comment]
Hmm... what source of sound are you using (file, wave...)? Also, what browser are you running it on?

**Comment by malorus** [comment]
I'm using file as source (mp3), using chrome 59 and firefox 54. I was lucky with no one of them...

**Comment by alemangui** [comment]
Can you create a jsfiddle with the issue and the mp3 file? I will take a look.

**Comment by malorus** [comment]
You'll find the code right here. But without the audio file. I tried to provide a full working example but I could not provide the audio file over https. So I give you the example right here. I have already checked multiple files and settings. The result: `release` does not have any effect, no matter what the value is. As mentioned, `attack `works fine.

```typescript
let sound = new Pizzicato.Sound('audio.mp3', function () {
        sound.attack = 0.01;
        sound.release = 5;
        sound.play();
});
```
I click on a button and a function is triggered which contains the code above.

A further observation: I recognised that chrome and firefox deliver different results to the same `attack` value. I have a cowbell with a hard attack. With the default value of 0.04 chrome already reduces subtly the punch whereas firefox not. Just for your information...

**Comment by alemangui** [comment]
Hey sorry for the late reply.

The release works basically when the ```pause``` or ```stop``` functions are used. When a sound file ends there is no release because none of the functions were invoked. Is this your use case?

**Comment by malorus** [comment]
No problem mate.

Ok, that explains it all. I thought the release would affect the end of a soundfile. But actually it only takes effect when pausing or stopping the file. It was my misconception. Do you think it might be a good idea to add an additional feature that adds a fade-out effect? Something like:
```typescript
sound.fadeout = 2000; // length in ms
```
There are use cases where this fadeout feature could avoid clips when the file itself was not faded out properly. The length determines when exactly the fadeout should begin. In the above example this should be 2s before the end of the file. So within these 2s the volume of the sound is going to be reduced linearily or logarithmically to 0. By default the fadeout is 0, meaning there should be no fadeout at all. Maybe this could be a further feature for a future release...?

**Comment by alemangui** [comment]
Thanks, it's an interesting proposal for the library. Given that it would only be useful for sounds loaded from files (which haven't been faded-out already) this feature will have a lower priority in the backlog than other ones in line. I will close this issue in the meantime, once/if the implementation is done I'll open a new one to avoid mixing topics.
