### ISSUE TITLE
Read compressedcontent in JSZip?

### ISSUE THREAD

**Issue by wildfiremedia** [alemangui/pizzicato#68]
How to read MP3 file in JSZip object's compressedcontent?
https://stuk.github.io/jszip/

// Point to zip file located in local disk...
    var loadmp3
    JSZipUtils.getBinaryContent('file:///.../.../b.zip', function(err, data) {
      if(err) { console.log(err) }
        JSZip.loadAsync(data).then(function (ee) {
        loadmp3 = ee.files["b.mp3"]._data.compressedContent
        var mp3 = new Pizzicato.Sound(loadmp3 ,function() {options: { detached: true }});
        mp3.play()
        });
    });

Google Chrome console:
Uncaught (in promise) Error: Error initializing Pizzicato Sound: Description type not supported. Initialize a sound using an object, a function or a string.

**Comment by alemangui** [comment]
I imagine the variable ```loadmp3``` is an array buffer or raw data? As of today unfortunately there is no way to instantiate a ```Pz.Sound``` from the data directly.
