### ISSUE TITLE
Can I synthesize sounds with Pizzicato.js?

### ISSUE THREAD

**Issue by mrrm92** [alemangui/pizzicato#70]
As in subject, I saw there are filters and waveshape generators.
Are also there LFOs, Envelopes and additive/subtractive/modulation synthesis techniques possible?

Thanks in advance for help.

**Comment by alemangui** [comment]
It is possible to use Pizzicato with base Web Audio nodes, which means that you can create whichever arrangement you need that may not be in Pizzicato (_e.g.,_ envelopes, modulation, etc).

The way this works is further detailed in the [using Pizzicato objects in a web audio graph](https://github.com/alemangui/pizzicato#using-pizzicato-objects-in-a-web-audio-graph) section of the docs. You could basically connect a web audio node to a ```Pz.Effect``` or connect a ```Pz.Sound``` to a web audio node for custom processing.
