### ISSUE TITLE
How do you play audio from mic, like in the demo page?

### ISSUE THREAD

**Issue by ricci07** [alemangui/pizzicato#71]
```
var voice = new Pizzicato.Sound({
    source: 'input',
    options: { volume: 0.8 }
});
//Doesn't do anything, so i tried adding
voice.play();
//I get exception about 'getRawSourceNode' is not a function
//How are you playing the mic audio stream when you hit the play button in the demo?
```

**Comment by alemangui** [comment]
This looks weird indeed. I was able to reproduce your problem in JsFiddle. I'll dig into it.

In the meantime and as a workaround placing the ```play``` function inside a callback will work:

```javascript
var voice = new Pizzicato.Sound({
    source: 'input',
    options: { volume: 0.8 }
}, function() {
    voice.play();
});
```

**Comment by alemangui** [comment]
Under the hood Pizzicato will call ```navigator.mediaDevices.getUserMedia``` (or equivalent) to get access to the mic. This function is asynchronous though, so the callback function must be used in order to use an input Pz.Sound.

**Comment by mastashake08** [comment]
When I do the callback it is iffy. Sometimes it works currently only twice.
