### ISSUE TITLE
event listener for an input audio

### ISSUE THREAD

**Issue by moahammadalt** [alemangui/pizzicato#72]
I want to simulate audio input from a mic to create an audio visualizer
is there is any event listener to catch instantly the frequency of the inserted audio input from a mic?

**Comment by alemangui** [comment]
I'm not sure I completely understand the use case. What exactly would the simulation of a mic input be needed in your case? If it is to test a visualization you can always use a few recorded samples with it. 

On the other hand, by "catching instantly the frequency" do you mean some sort of frequency detection mechanism (e.g., guitar tuner)?

**Comment by alemangui** [comment]
Hey I will close this issue but let me know of you have some more specific use case and we'll go over it.
