### ISSUE TITLE
getByteFrequencyData - issue?

### ISSUE THREAD

**Issue by schema0708** [alemangui/pizzicato#76]
Hi,

I would like to use Pizzicato, with Three JS to create a sound visualizer, but for some reason after I create my frequencyData, it returning a frequency of 0 for each band. Is there something that I'm missing in order to get these frequencies so I can them manipulate my meshes with Three JS, please let me know?. I've attached a screenshot of my console window, and pasted my code below for reference.

`var context = Pizzicato.context;
var  analyser = context.createAnalyser();

var   ambient = new Pizzicato.Sound('./mp3/ambient.mp3', playAmbient);
ambient.loop = true;
ambient.volume = 1;
ambient.connect(analyser);

var  frequencyData = new Uint8Array(analyser.frequencyBinCount);
console.log("Frequency Data: " , frequencyData);
console.log("Frequency Data Length: " , frequencyData.length);`

function playAmbient(e)
{
 console.log("playAmbient();");
 ambient.play();
}`

Thanks,

Abel

![screenshot](https://user-images.githubusercontent.com/3027843/33505582-c6431b20-d6a0-11e7-87fa-d389d477af6e.jpg)

**Comment by midipixel** [comment]
Hey Abel, you must connect your analyser node to Pizzicato's masterGainNode, instead of connecting it to the Sound Object:

`Pizzicato.masterGainNode.connect(analyser);`

**Comment by schema0708** [comment]
Thanks for the reply but I managed to figure it out on my own.
