### ISSUE TITLE
playback file before completely downloaded

### ISSUE THREAD

**Issue by malorus** [alemangui/pizzicato#77]
Hi, I just wanted to playback a large file. But I recognised that Pizzicato plays the file after it has been completely downloaded. This leads to a big delay at the beginning. Is there any way to playback files while downloading them? So that it plays the parts that are already available without waiting for the entire file.
greetz,
malorus

**Comment by alemangui** [comment]
Hey, sorry for the late reply. Unfortunately Pizzicato can't currently do that by itself. You might be able to cook something up using streams + the fetch API, but Pz won't be of much help on that :(
