### ISSUE TITLE
Problem with removeEffect() and groups

### ISSUE THREAD

**Issue by miikakuisma** [alemangui/pizzicato#78]
Thanks for making this awesome library!

I've group of sounds and I'm adding multiple effects on the group. Everything works great except if I'm removing effects. If there are more than 1 effect on the group then: removing any other effect except the first one will produce error: `TypeError: this.effectConnectors is not a function`

If I remove the effects in the same order as I've added them, then no errors happening.

I'm using v0.6.2 via NPM

**Comment by alemangui** [comment]
Sorry for the late reply and thanks for raising this issue. I will take a look at this. Probably linked to commit 62ac78e from issue #42

**Comment by alemangui** [comment]
The fix is in master and will be present in the next release 👍
