### ISSUE TITLE
Playing sound right after another one finishes and sync

### ISSUE THREAD

**Issue by hovi** [alemangui/pizzicato#83]
Hi,

I was wondering if there's a guaranteed way to play 2 sounds right after eachother. I need perfect timing as those are music samples. Is `sound.on("end"...` way to go or can you point me into a direction? I saw #73 , but that has to be horribly inaccurate for my purpose.

And then I got even more complicated possibility I am considering - I have some initial track (probably groups actually), then track, that loops for some time (not known at start) and then when loop gets interrupted (meaning it finished till end, but doesn't start again), ending track plays until the end. Is there way to achieve that?

Cheers, great lib.

**Comment by alemangui** [comment]
Accurate timing will be tough with the triggers and callbacks :(  The only way I can think of having more precise timing is to use the parameters in the ```play``` function to specify the exact start time, notably the ```when``` and ```offset``` params.

https://github.com/alemangui/pizzicato#play-example

**Comment by alemangui** [comment]
Closing this, let me know if you encounter issues with the ```play``` parameters.
