### ISSUE TITLE
Using pizzicato only to add sound effects

### ISSUE THREAD

**Issue by dfromero** [alemangui/pizzicato#85]
I've got a webaudio based application that is highly coupled with howlerjs, would it be possible to use pizzicato to add effects to a howlerjs sound (accessing low level api exposed by the object) ?

**Comment by nascent** [comment]
From my understanding, Pizzicato is designed to work standalone, and you can (if you wish) pass audio to the Web Audio API via Pizzicatos' AudioContext.

**Comment by alemangui** [comment]
@dfromero, I'll close this, the link sent by @evoyy should details how to use the effects on standalone. Feel free to reopen if you encounter issues.
