### ISSUE TITLE
Loop attribute not working 

### ISSUE THREAD

**Issue by brunotome** [alemangui/pizzicato#87]
var homeLoopAudio = new Pizzicato.Sound({
        source: 'file',
        loop: true,
        options: { 
          path: audiosHome[randomVariable],
          volume: 0.1 
        }
      }, function() {
        homeLoopAudio.play();
      });

The loop is not working, and i don't know why. Anyone with the same problem?

**Comment by alemangui** [comment]
The loop option should be inside the ```options``` object:

```javascript
var toto = new Pz.Sound({ 
  source: 'file', 
  options: { 
    path: 'some-audio-file.mp3', 
    loop: true 
  }
}
```

More info here: https://github.com/alemangui/pizzicato#sounds-from-a-file-example
