### ISSUE TITLE
The offset is imprecise in a sound with a file source that loops

### ISSUE THREAD

**Issue by alemangui** [alemangui/pizzicato#9]
This issue occurs with Pizzicato.Sound objects that have a file as a source and have the ```loop: true``` attribute. After the first looping occurs, the offset becomes imprecise

This can be evidenced by calling ```sound.pause(); sound.play();```. After the first loop the cut will not be seamless and a jump will be heard.

Another way is to add and remove an effect to the sound: ```sound.addEffect(effect); sound.removeEffect(effect)```. After the first loop the operation will not be smooth. This is exemplified by @JohnPaulHarold in [this demo site.](http://webui.lt/pz_fx_test/examples/effects_on_off.html)

**Comment by JohnPaulHarold** [comment]
nice work
