### ISSUE TITLE
How do I generate a random frequency noise instead of white noise?

### ISSUE THREAD

**Issue by zhengyanhu** [alemangui/pizzicato#90]
I get a demand that users can hear different frequencies of noise, how can I achieve this?

**Comment by alemangui** [comment]
Hi @zhengyanhu, I can't help you with the specific implementation of the noise function, but you can integrate it into a Pizzicato by creating a [Sound from an audio function](https://github.com/alemangui/pizzicato#sounds-from-a-function).

Some information and example codes about different kinds of noise can be found here: https://noisehack.com/generate-noise-web-audio-api/
