### ISSUE TITLE
can i use it in node.js

### ISSUE THREAD

**Issue by Girlsmile** [alemangui/pizzicato#96]

**Comment by MyZeD** [comment]
Sure, check out https://www.npmjs.com/package/pizzicato

**Comment by alemangui** [comment]
Hi @Girlsmile 

Pizzicato uses the webaudio API, which is present in the browser but not in a NodeJS backend. 

There are some projects that attempt to implement the web audio API in Node (like https://github.com/audiojs/web-audio-api). I haven't tried them myself but that could be a solution.
